### ISSUE TITLE
add issue - help description inaccurate

### ISSUE THREAD

**Issue by dmarsic** [yassinemaaroufi/cit#1]
Hi Yassine,

I'm testing cit and I think it might be quite useful. I noticed the error with help description for cit add:

```
cit add issue-id        Add new issues
```

add doesn't accept issue-id but a description.

I'd like to add a feature request, if possible. When cit add is specified with no description, open an editor, similar to what happens when cit edit issue-id is called.

Thanks.

**Comment by yassinemaaroufi** [comment]
Hi,

Thank you for getting in touch.
I fixed the help message as you suggested.
You are welcome to add more features just let me know when you are finished with a pull request so I can include your modifications in the code.

Best regards,

**Comment by dmarsic** [comment]
Thanks for fixing, the message now looks correct.
Sure, if I find something to contribute, I'll gladly do so.
